"""empty message

Revision ID: c58ede5e980d
Revises:
Create Date: 2024-10-05 21:47:52.484963

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c58ede5e980d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pre_billing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('check_in_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('check_out_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pre_billing', schema=None) as batch_op:
        batch_op.drop_column('check_out_time')
        batch_op.drop_column('check_in_time')

    with op.batch_alter_table('med_error_reasons', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)

    with op.batch_alter_table('med_actions', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)

    with op.batch_alter_table('med_action_statuses', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
